import HorizontalStory from "../../../components/HorizontalStoryItem";
import CommentCard from "../../../components/CommentCardItem";
import NewStory from "../../../components/NewStory";
import { categories, commentItem } from "../../../data/testData";
import RatingList from "../../../components/RatingList";

const Section2 = ({topNew}) => {
  console.log("NEW STORIESSSSSSSS: ", topNew.data)
  const newStory = [
    {
        "title": "Bắt Đầu 10 Lần Rút Sau Đó Vô Địch",
        "coverImage": "https://media.toidoc.vn/story-coverbat-dau-10-lan-rut-sau-do-vo-dich,bat-dau-10-lan-rut-sau-do-vo-dich-1705563777080.jpg",
        "slug": "bat-dau-10-lan-rut-sau-do-vo-dich",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 4.0,
        "totalView": 25695,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "https://media.toidoc.io/story-cover/the-loai/huyen-huyen-1705315177154.png",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 11396,
                "metaDescription": "Truyện huyền huyễn hay được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện huyền huyễn này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Huyền Huyễn, truyện huyền huyễn, truyện huyền huyễn hay, truyện huyền huyễn ngôn tình, truyện huyền huyễn cổ đại, truyện huyền huyễn full, list truyện huyền huyễn",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": "https://truyenfull.com/truyen-huyen-huyen/",
                "bgColor": "",
                "orderCategory": 24,
                "totalFollows": -2,
                "type": "ACTION"
            },
            {
                "id": "63ba8d77cd9fcb5742949d07",
                "code": "xuyen-khong",
                "name": "Xuyên Không",
                "image": "https://media.toidoc.io/story-cover/the-loai/xuyen-khong-1705315392493.png",
                "slug": "/the-loai/xuyen-khong",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 16656,
                "metaDescription": "Top các truyện xuyên không hấp dẫn cùng với bộ sưu tập của chúng tôi, bạn có thể xem ngay tại Toidoc. Sản phẩm được hỗ trợ trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện xuyên không, xuyên không, truyen xuyen khong, truyện xuyên không cổ đại, xuyên không quân sự, xuyên không y thuật, xuyên không hay nhất, truyện xuyên không nữ cường, xuyên không hay nhất mọi thời đại",
                "originUrl": "https://truyenfull.vn/the-loai/xuyen-khong/",
                "originUrlFullCom": "https://truyenfull.com/truyen-xuyen-khong/",
                "bgColor": "",
                "orderCategory": 12,
                "totalFollows": 0,
                "type": "ROMANCE"
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "https://media.toidoc.io/story-cover/the-loai/tien-hiep-1705575452901.png",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4129,
                "metaDescription": "Danh sách truyện tiên hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện tiên hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện tiên hiệp, tiên hiệp, tiên hiệp hay, truyện tiên hiệp full hay, truyện tiên hiệp hay nhất, truyện tiên hiệp mới truyện tiên hiệp mới nhất, truyen tien hiep, truyện tiên hiệp audio, truyện tiên hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-tien-hiep/",
                "bgColor": "bg-tien-hiep",
                "orderCategory": 23,
                "totalFollows": 2150,
                "type": "ACTION"
            }
        ]
    },
    {
        "title": "Chung Cực Toàn Năng Học Sinh",
        "coverImage": "https://media.toidoc.vn/story-coverchung-cuc-toan-nang-hoc-sinh,chung-cuc-toan-nang-hoc-sinh-1705573044273.jpg",
        "slug": "chung-cuc-toan-nang-hoc-sinh",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 4.0,
        "totalView": 165,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949d04",
                "code": "di-nang",
                "name": "Dị Năng",
                "image": "https://media.toidoc.io/story-cover/the-loai/di-nang-1705315064842.png",
                "slug": "/the-loai/di-nang",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 2412,
                "metaDescription": "Truyện dị năng full hay nhất có tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện dị năng này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Dị năng, truyện dị năng, truyen di nang, truyện dị năng hay, truyện dị năng hay full, truyện dị năng hay nhất, dị năng hoàn, dị năng mạt thế, dị năng giao su",
                "originUrl": "https://truyenfull.vn/the-loai/di-nang/",
                "originUrlFullCom": "https://truyenfull.com/truyen-di-nang/",
                "bgColor": "",
                "orderCategory": 28,
                "totalFollows": 1,
                "type": "ACTION"
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949d13",
                "code": "do-thi",
                "name": "Đô Thị",
                "image": "https://media.toidoc.io/story-cover/the-loai/do-thi-1705315093622.png",
                "slug": "/the-loai/do-thi",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 8190,
                "metaDescription": "Truyện đô thị full được chọn lọc và cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện đô thị này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "truyện đô thị, truyện đô thị full, truyện đô thị tu chân, truyện đô thị mới, truyện đô thị đỉnh phong, truyện đô thị hệ thống",
                "originUrl": "https://truyenfull.vn/the-loai/do-thi/",
                "originUrlFullCom": "https://truyenfull.com/truyen-do-thi/",
                "bgColor": "",
                "orderCategory": 6,
                "totalFollows": -1,
                "type": "ROMANCE"
            }
        ]
    },
    {
        "title": "Vạn Cổ Chí Tôn",
        "coverImage": "https://yymedia.codeprime.net/media/novels/4f4a2e6d7d.jpg",
        "slug": "van-co-chi-ton",
        "status": "ACTIVE",
        "thumbnail": "van-co-chi-ton-1711474010826.jpg",
        "rate": 3.85,
        "totalView": 1396,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 11396,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "https://media.toidoc.io/the-loai/tien-hiep.png",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4129,
                "metaDescription": "Danh sách truyện tiên hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện tiên hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện tiên hiệp, tiên hiệp, tiên hiệp hay, truyện tiên hiệp full hay, truyện tiên hiệp hay nhất, truyện tiên hiệp mới truyện tiên hiệp mới nhất, truyen tien hiep, truyện tiên hiệp audio, truyện tiên hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-tien-hiep/",
                "bgColor": "bg-tien-hiep",
                "orderCategory": 5,
                "totalFollows": 533,
                "type": null
            }
        ]
    },
    {
        "title": "Đường Tăng Đánh Xuyên Tây Du",
        "coverImage": "https://media.toidoc.vn/story-coverduong-tang-danh-xuyen-tay-du,duong-tang-danh-xuyen-tay-du-1701080558207.jpeg",
        "slug": "duong-tang-danh-xuyen-tay-du",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 5.0,
        "totalView": 63,
        "categories": [],
        "mainCategories": []
    },
    {
        "title": "hệ thống nhân vật phản diện mạnh nhất",
        "coverImage": "https://media.toidoc.vn/story-coverhe-thong-nhan-vat-phan-dien-manh-nhat,he-thong-nhan-vat-phan-dien-manh-nhat-1703063728715.jpg",
        "slug": "he-thong-nhan-vat-phan-dien-manh-nhat",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": null,
        "totalView": 22,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cfb",
                "code": "kiem-hiep",
                "name": "Kiếm Hiệp",
                "image": "https://media.toidoc.io/the-loai/Kiem-hiep.png",
                "slug": "/the-loai/kiem-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 2713,
                "metaDescription": "Danh sách truyện kiếm hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện kiếm hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện kiếm hiệp, kiếm hiệp, kiếm hiệp hay, truyện kiếm hiệp hay nhất, truyện kiếm hiệp cổ long, truyện kiếm hiệp full, truyện kiếm hiệp online, truyen kiem hiep, truyện kiếm hiệp a-z, truyện kiếm hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/kiem-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-kiem-hiep/",
                "bgColor": "",
                "orderCategory": 6,
                "totalFollows": 1,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d01",
                "code": "he-thong",
                "name": "Hệ Thống",
                "image": "https://media.toidoc.io/the-loai/he-thong.png",
                "slug": "/the-loai/he-thong",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4262,
                "metaDescription": "Top truyện hệ thống hay được tổng hợp nhanh tại Toidoc. Bạn có thể nhanh chóng tìm các truyện hệ thống này trên nhiều nền tảng khác nhau.",
                "metaKeywords": "Truyện hệ thống, truyện hệ thống full, truyện hệ thống hay nhất, truyện hệ thống đô thị, truyện hệ thống sắc, truyện hệ thống xuyên nhanh, truyện hệ thống tu tiên, truyện hệ thống xuyên không hệ thống, hệ thống trưởng môn",
                "originUrl": "https://truyenfull.vn/the-loai/he-thong/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": 17,
                "totalFollows": null,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949cfb",
                "code": "kiem-hiep",
                "name": "Kiếm Hiệp",
                "image": "https://media.toidoc.io/the-loai/Kiem-hiep.png",
                "slug": "/the-loai/kiem-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 2713,
                "metaDescription": "Danh sách truyện kiếm hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện kiếm hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện kiếm hiệp, kiếm hiệp, kiếm hiệp hay, truyện kiếm hiệp hay nhất, truyện kiếm hiệp cổ long, truyện kiếm hiệp full, truyện kiếm hiệp online, truyen kiem hiep, truyện kiếm hiệp a-z, truyện kiếm hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/kiem-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-kiem-hiep/",
                "bgColor": "",
                "orderCategory": 6,
                "totalFollows": 1,
                "type": null
            }
        ]
    },
    {
        "title": "Siêu Cấp Thần Cơ Nhân (Full-Dịch)",
        "coverImage": "https://media.toidoc.vn/story-coversieu-cap-than-co-nhan-full-dich,sieu-cap-than-co-nhan-full-dich-1702615653384.jpeg",
        "slug": "sieu-cap-than-co-nhan-full-dich",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 4.0,
        "totalView": 250,
        "categories": [],
        "mainCategories": []
    },
    {
        "title": "Cô Vợ Ngọt Ngào Có Chút Bất Lương (Vợ Mới Bất Lương Có Chút Ngọt)",
        "coverImage": "https://i.pinimg.com/564x/3b/5a/0b/3b5a0bef39e7c1f8b2f07d482c05a3b0.jpg",
        "slug": "co-vo-ngot-ngao-co-chut-bat-luong-vo-moi-bat-luong-co-chut-ngot",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 4.75,
        "totalView": 55795,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cfc",
                "code": "ngon-tinh",
                "name": "Ngôn Tình",
                "image": "https://media.toidoc.io/the-loai/ngon-tinh.png",
                "slug": "/the-loai/ngon-tinh",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 33631,
                "metaDescription": "Danh sách truyện ngôn tình hay được cập nhật liên tục mới nhất. Bạn có thể phân loại, sắp xếp, lọc các truyện ngôn tình này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện ngôn tình, ngôn tình, truyen ngon tinh, truyện ngôn tình hay nhất, truyện ngôn tình ngắn, truyện ngôn tình hài, list truyện ngôn tình, trùm truyện ngôn tình, truyện ngôn tình hoàn, truyện ngôn tình full hay nhất, truyện ngôn tình mới",
                "originUrl": "https://truyenfull.vn/the-loai/ngon-tinh/",
                "originUrlFullCom": "https://truyenfull.com/truyen-ngon-tinh/",
                "bgColor": "#232C89",
                "orderCategory": 1,
                "totalFollows": 620,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d09",
                "code": "trong-sinh",
                "name": "Trùng Sinh",
                "image": "https://media.toidoc.io/the-loai/trong-sinh.png",
                "slug": "/the-loai/trong-sinh",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 7130,
                "metaDescription": "Tuyển tập truyện Trùng Sinh (trùng sinh) hay mới nhất kể về sự hồi sinh của nhân vật chính vào một người khác có thể là xuyên không. Truyện được cập nhật nhanh tại Toidoc",
                "metaKeywords": "trọng sinh, trùng sinh, trong sinh, truyện trọng sinh, truyện trùng sinh, trọng sinh cổ đại, trọng sinh hay nhất, trọng sinh cổ đại hoàn, list truyện trọng sinh, trọng sinh hiện đại, truyện trọng sinh đam mỹ",
                "originUrl": "https://truyenfull.vn/the-loai/trong-sinh/",
                "originUrlFullCom": "https://truyenfull.com/truyen-trong-sinh/",
                "bgColor": "",
                "orderCategory": 14,
                "totalFollows": 1,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d0e",
                "code": "sung",
                "name": "Sủng",
                "image": "https://media.toidoc.io/the-loai/sung.png",
                "slug": "/the-loai/sung",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 13151,
                "metaDescription": "Truyện ngôn tình sủng chọn lọc đặc sắc được tổng cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện sủng này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện sủng, truyện sủng hoàn, truyện ngôn tình sủng, truyện sủng ngọt, trùm truyện sủng, truyen sung, sung, sủng",
                "originUrl": "https://truyenfull.vn/the-loai/sung/",
                "originUrlFullCom": "https://truyenfull.com/truyen-sung/",
                "bgColor": "#09B29A",
                "orderCategory": 4,
                "totalFollows": -1,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949cfc",
                "code": "ngon-tinh",
                "name": "Ngôn Tình",
                "image": "https://media.toidoc.io/the-loai/ngon-tinh.png",
                "slug": "/the-loai/ngon-tinh",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 33631,
                "metaDescription": "Danh sách truyện ngôn tình hay được cập nhật liên tục mới nhất. Bạn có thể phân loại, sắp xếp, lọc các truyện ngôn tình này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện ngôn tình, ngôn tình, truyen ngon tinh, truyện ngôn tình hay nhất, truyện ngôn tình ngắn, truyện ngôn tình hài, list truyện ngôn tình, trùm truyện ngôn tình, truyện ngôn tình hoàn, truyện ngôn tình full hay nhất, truyện ngôn tình mới",
                "originUrl": "https://truyenfull.vn/the-loai/ngon-tinh/",
                "originUrlFullCom": "https://truyenfull.com/truyen-ngon-tinh/",
                "bgColor": "#232C89",
                "orderCategory": 1,
                "totalFollows": 642,
                "type": null
            }
        ]
    },
    {
        "title": "Trọng Sinh Chi Tối Cường Kiếm Thần",
        "coverImage": "https://media.toidoc.vn/story-covertrong-sinh-chi-toi-cuong-kiem-than,trong-sinh-chi-toi-cuong-kiem-than-1705396135177.jpg",
        "slug": "trong-sinh-chi-toi-cuong-kiem-than",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 4.0,
        "totalView": 30154,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cff",
                "code": "vong-du",
                "name": "Võng Du",
                "image": "https://media.toidoc.io/story-cover/the-loai/vong-du-1705315402917.png",
                "slug": "/the-loai/vong-du",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 1553,
                "metaDescription": "Truyện võng du hay nhất được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện võng du hay này trên nhiều nền tảng khác nhau.",
                "metaKeywords": "Tuyện võng du, truyện võng du hay nhất, truyện võng du full, truyện võng du ngôn tình, truyện võng du hệ thống, võng du, vong du, truyen vong du",
                "originUrl": "https://truyenfull.vn/the-loai/vong-du/",
                "originUrlFullCom": "https://truyenfull.com/truyen-vong-du/",
                "bgColor": "",
                "orderCategory": 34,
                "totalFollows": 0,
                "type": "ACTION"
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949cff",
                "code": "vong-du",
                "name": "Võng Du",
                "image": "https://media.toidoc.io/story-cover/the-loai/vong-du-1705315402917.png",
                "slug": "/the-loai/vong-du",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 1553,
                "metaDescription": "Truyện võng du hay nhất được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện võng du hay này trên nhiều nền tảng khác nhau.",
                "metaKeywords": "Tuyện võng du, truyện võng du hay nhất, truyện võng du full, truyện võng du ngôn tình, truyện võng du hệ thống, võng du, vong du, truyen vong du",
                "originUrl": "https://truyenfull.vn/the-loai/vong-du/",
                "originUrlFullCom": "https://truyenfull.com/truyen-vong-du/",
                "bgColor": "",
                "orderCategory": 34,
                "totalFollows": 0,
                "type": "ACTION"
            }
        ]
    },
    {
        "title": "Mỹ Thực Gia Ở Dị Giới",
        "coverImage": "https://media.toidoc.vn/story-covermy-thuc-gia-o-di-gioi,my-thuc-gia-o-di-gioi-1703061811040.jpg",
        "slug": "my-thuc-gia-o-di-gioi",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 5.0,
        "totalView": 3961,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "https://media.toidoc.io/the-loai/huyen-huyen.png",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 11396,
                "metaDescription": "Truyện huyền huyễn hay được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện huyền huyễn này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Huyền Huyễn, truyện huyền huyễn, truyện huyền huyễn hay, truyện huyền huyễn ngôn tình, truyện huyền huyễn cổ đại, truyện huyền huyễn full, list truyện huyền huyễn",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": "https://truyenfull.com/truyen-huyen-huyen/",
                "bgColor": "",
                "orderCategory": 12,
                "totalFollows": -2,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949d03",
                "code": "di-gioi",
                "name": "Dị Giới",
                "image": "https://media.toidoc.io/the-loai/di-gioi.png",
                "slug": "/the-loai/di-gioi",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4756,
                "metaDescription": "Truyện dị giới full hay nhất có tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện dị giới này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Dị giới, truyện dị giới, truyen di gioi, truyện dị giới hay, truyện xuyên không dị giới, dị giới nữ cường, dị giới dược sư, dị giới sắc, dị giới full",
                "originUrl": "https://truyenfull.vn/the-loai/di-gioi/",
                "originUrlFullCom": "https://truyenfull.com/truyen-di-gioi/",
                "bgColor": "",
                "orderCategory": 18,
                "totalFollows": null,
                "type": null
            }
        ]
    },
    {
        "title": "Khủng Bố Sống Lại",
        "coverImage": "https://media.toidoc.vn/story-coverkhung-bo-song-lai,khung-bo-song-lai-1704871150963.jpg",
        "slug": "khung-bo-song-lai",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 3.9,
        "totalView": 53,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949d0c",
                "code": "linh-di",
                "name": "Linh Dị",
                "image": "https://media.truyenso1.xyz/story-cover/the-loai/linh-di-1705315222500.png",
                "slug": "/the-loai/linh-di",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 2984,
                "metaDescription": "Tuyển tập các truyện linh dị kể về các câu chuyện có tình tiết kì lạ, huyền bí, thần bí. Truyện có tính giải trí cao, hấp dẫn và liên tục được cập nhật tại Toidoc",
                "metaKeywords": "Linh dị, truyện linh dị, truyen linh di, truyện linh dị hay, truyện linh dị ngôn tình, truyện linh dị full, list truyện linh dị, linh dị hoàn, truyện ma ngôn tình, truyện ma",
                "originUrl": "https://truyenfull.vn/the-loai/linh-di/",
                "originUrlFullCom": "https://truyenfull.com/truyen-linh-di/",
                "bgColor": "",
                "orderCategory": 13,
                "totalFollows": 0,
                "type": "ACTION"
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949d0c",
                "code": "linh-di",
                "name": "Linh Dị",
                "image": "https://media.truyenso1.xyz/story-cover/the-loai/linh-di-1705315222500.png",
                "slug": "/the-loai/linh-di",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 2984,
                "metaDescription": "Tuyển tập các truyện linh dị kể về các câu chuyện có tình tiết kì lạ, huyền bí, thần bí. Truyện có tính giải trí cao, hấp dẫn và liên tục được cập nhật tại Toidoc",
                "metaKeywords": "Linh dị, truyện linh dị, truyen linh di, truyện linh dị hay, truyện linh dị ngôn tình, truyện linh dị full, list truyện linh dị, linh dị hoàn, truyện ma ngôn tình, truyện ma",
                "originUrl": "https://truyenfull.vn/the-loai/linh-di/",
                "originUrlFullCom": "https://truyenfull.com/truyen-linh-di/",
                "bgColor": "",
                "orderCategory": 13,
                "totalFollows": 0,
                "type": "ACTION"
            }
        ]
    },
    {
        "title": "Ngạo Thế Cửu Trọng Thiên",
        "coverImage": "https://media.toidoc.vn/story-coverngao-the-cuu-trong-thien,ngao-the-cuu-trong-thien-1702623808528.jpeg",
        "slug": "ngao-the-cuu-trong-thien",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 3.8,
        "totalView": 1262,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "https://media.toidoc.io/the-loai/tien-hiep.png",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4129,
                "metaDescription": "Danh sách truyện tiên hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện tiên hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện tiên hiệp, tiên hiệp, tiên hiệp hay, truyện tiên hiệp full hay, truyện tiên hiệp hay nhất, truyện tiên hiệp mới truyện tiên hiệp mới nhất, truyen tien hiep, truyện tiên hiệp audio, truyện tiên hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-tien-hiep/",
                "bgColor": "bg-tien-hiep",
                "orderCategory": 5,
                "totalFollows": 864,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949cfb",
                "code": "kiem-hiep",
                "name": "Kiếm Hiệp",
                "image": "https://media.toidoc.io/the-loai/Kiem-hiep.png",
                "slug": "/the-loai/kiem-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 2713,
                "metaDescription": "Danh sách truyện kiếm hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện kiếm hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện kiếm hiệp, kiếm hiệp, kiếm hiệp hay, truyện kiếm hiệp hay nhất, truyện kiếm hiệp cổ long, truyện kiếm hiệp full, truyện kiếm hiệp online, truyen kiem hiep, truyện kiếm hiệp a-z, truyện kiếm hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/kiem-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-kiem-hiep/",
                "bgColor": "",
                "orderCategory": 6,
                "totalFollows": 1,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "https://media.toidoc.io/the-loai/huyen-huyen.png",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 11396,
                "metaDescription": "Truyện huyền huyễn hay được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện huyền huyễn này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Huyền Huyễn, truyện huyền huyễn, truyện huyền huyễn hay, truyện huyền huyễn ngôn tình, truyện huyền huyễn cổ đại, truyện huyền huyễn full, list truyện huyền huyễn",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": "https://truyenfull.com/truyen-huyen-huyen/",
                "bgColor": "",
                "orderCategory": 12,
                "totalFollows": -2,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "https://media.toidoc.io/the-loai/huyen-huyen.png",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 11396,
                "metaDescription": "Truyện huyền huyễn hay được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện huyền huyễn này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Huyền Huyễn, truyện huyền huyễn, truyện huyền huyễn hay, truyện huyền huyễn ngôn tình, truyện huyền huyễn cổ đại, truyện huyền huyễn full, list truyện huyền huyễn",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": "https://truyenfull.com/truyen-huyen-huyen/",
                "bgColor": "",
                "orderCategory": 12,
                "totalFollows": -2,
                "type": null
            }
        ]
    },
    {
        "title": "Đại Đạo Độc Hành",
        "coverImage": "https://media.toidoc.vn/story-coverdai-dao-doc-hanh-1697769556312.jpg",
        "slug": "dai-dao-doc-hanh",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 4.2,
        "totalView": 3042,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4129,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 11396,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949cfb",
                "code": "kiem-hiep",
                "name": "Kiếm Hiệp",
                "image": "https://media.toidoc.io/the-loai/Kiem-hiep.png",
                "slug": "/the-loai/kiem-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 2713,
                "metaDescription": "Danh sách truyện kiếm hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện kiếm hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện kiếm hiệp, kiếm hiệp, kiếm hiệp hay, truyện kiếm hiệp hay nhất, truyện kiếm hiệp cổ long, truyện kiếm hiệp full, truyện kiếm hiệp online, truyen kiem hiep, truyện kiếm hiệp a-z, truyện kiếm hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/kiem-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-kiem-hiep/",
                "bgColor": "",
                "orderCategory": 6,
                "totalFollows": 1,
                "type": null
            }
        ]
    },
    {
        "title": "Thần Cấp Đại Ma Đầu",
        "coverImage": "https://media.toidoc.vn/story-coverthan-cap-dai-ma-dau,than-cap-dai-ma-dau-1702883855645.jpg",
        "slug": "than-cap-dai-ma-dau",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 5.0,
        "totalView": 91,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "https://media.toidoc.io/the-loai/tien-hiep.png",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4129,
                "metaDescription": "Danh sách truyện tiên hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện tiên hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện tiên hiệp, tiên hiệp, tiên hiệp hay, truyện tiên hiệp full hay, truyện tiên hiệp hay nhất, truyện tiên hiệp mới truyện tiên hiệp mới nhất, truyen tien hiep, truyện tiên hiệp audio, truyện tiên hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-tien-hiep/",
                "bgColor": "bg-tien-hiep",
                "orderCategory": 5,
                "totalFollows": 1402,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d00",
                "code": "khoa-huyen",
                "name": "Khoa Huyễn",
                "image": "https://media.toidoc.io/the-loai/khoa-huyen.png",
                "slug": "/the-loai/khoa-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 2594,
                "metaDescription": "Danh sách truyện khoa huyễn chọn lọc được tổng hợp cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện khoa huyễn này trên nhiều nền tảng khác nhau.",
                "metaKeywords": "khoa huyễn, truyện khoa huyễn, truyện khoa huyễn full, truyện khoa huyễn mạt thế, truyện khoa huyễn hay nhất, truyện khoa huyễn mới",
                "originUrl": "https://truyenfull.vn/the-loai/khoa-huyen/",
                "originUrlFullCom": "https://truyenfull.com/truyen-khoa-huyen/",
                "bgColor": "",
                "orderCategory": 13,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "https://media.toidoc.io/the-loai/huyen-huyen.png",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 11396,
                "metaDescription": "Truyện huyền huyễn hay được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện huyền huyễn này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Huyền Huyễn, truyện huyền huyễn, truyện huyền huyễn hay, truyện huyền huyễn ngôn tình, truyện huyền huyễn cổ đại, truyện huyền huyễn full, list truyện huyền huyễn",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": "https://truyenfull.com/truyen-huyen-huyen/",
                "bgColor": "",
                "orderCategory": 12,
                "totalFollows": -2,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d13",
                "code": "do-thi",
                "name": "Đô Thị",
                "image": "https://media.toidoc.io/the-loai/do-thi.png",
                "slug": "/the-loai/do-thi",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 8190,
                "metaDescription": "Truyện đô thị full được chọn lọc và cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện đô thị này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "truyện đô thị, truyện đô thị full, truyện đô thị tu chân, truyện đô thị mới, truyện đô thị đỉnh phong, truyện đô thị hệ thống",
                "originUrl": "https://truyenfull.vn/the-loai/do-thi/",
                "originUrlFullCom": "https://truyenfull.com/truyen-do-thi/",
                "bgColor": "",
                "orderCategory": 10,
                "totalFollows": -1,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d1f",
                "code": "khac",
                "name": "Khác",
                "image": "https://media.toidoc.io/the-loai/khac.png",
                "slug": "/the-loai/khac",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 11015,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/khac/",
                "originUrlFullCom": "https://truyenfull.com/truyen-khac/",
                "bgColor": "",
                "orderCategory": 30,
                "totalFollows": null,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949d00",
                "code": "khoa-huyen",
                "name": "Khoa Huyễn",
                "image": "https://media.toidoc.io/the-loai/khoa-huyen.png",
                "slug": "/the-loai/khoa-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 2594,
                "metaDescription": "Danh sách truyện khoa huyễn chọn lọc được tổng hợp cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện khoa huyễn này trên nhiều nền tảng khác nhau.",
                "metaKeywords": "khoa huyễn, truyện khoa huyễn, truyện khoa huyễn full, truyện khoa huyễn mạt thế, truyện khoa huyễn hay nhất, truyện khoa huyễn mới",
                "originUrl": "https://truyenfull.vn/the-loai/khoa-huyen/",
                "originUrlFullCom": "https://truyenfull.com/truyen-khoa-huyen/",
                "bgColor": "",
                "orderCategory": 13,
                "totalFollows": null,
                "type": null
            }
        ]
    },
    {
        "title": "Người Đưa Thư Khủng Bố ",
        "coverImage": "https://media.toidoc.vn/story-covernguoi-dua-thu-khung-bo-,nguoi-dua-thu-khung-bo--1706153485659.jpg",
        "slug": "nguoi-dua-thu-khung-bo-",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": null,
        "totalView": 145,
        "categories": [],
        "mainCategories": []
    },
    {
        "title": "Vô Địch Thiên Đế",
        "coverImage": "https://media.toidoc.vn/story-covervo-dich-thien-de,vo-dich-thien-de-1702437798493.jpg",
        "slug": "vo-dich-thien-de",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 4.2,
        "totalView": 9142,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "https://media.toidoc.io/the-loai/tien-hiep.png",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4129,
                "metaDescription": "Danh sách truyện tiên hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện tiên hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện tiên hiệp, tiên hiệp, tiên hiệp hay, truyện tiên hiệp full hay, truyện tiên hiệp hay nhất, truyện tiên hiệp mới truyện tiên hiệp mới nhất, truyen tien hiep, truyện tiên hiệp audio, truyện tiên hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-tien-hiep/",
                "bgColor": "bg-tien-hiep",
                "orderCategory": 5,
                "totalFollows": 856,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "https://media.toidoc.io/the-loai/tien-hiep.png",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4129,
                "metaDescription": "Danh sách truyện tiên hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện tiên hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện tiên hiệp, tiên hiệp, tiên hiệp hay, truyện tiên hiệp full hay, truyện tiên hiệp hay nhất, truyện tiên hiệp mới truyện tiên hiệp mới nhất, truyen tien hiep, truyện tiên hiệp audio, truyện tiên hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-tien-hiep/",
                "bgColor": "bg-tien-hiep",
                "orderCategory": 5,
                "totalFollows": 856,
                "type": null
            }
        ]
    },
    {
        "title": "Vĩnh Hằng Thánh Vương",
        "coverImage": "https://cdn.truyenfull.com/medias/covers/24/24798-vinh-hang-thanh-vuong-c_cover_large.jpg",
        "slug": "vinh-hang-thanh-vuong-c",
        "status": "ACTIVE",
        "thumbnail": "vinh-hang-thanh-vuong-c-1711474269820.jpg",
        "rate": 4.0,
        "totalView": 2748,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4129,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-tien-hiep/",
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            }
        ],
        "mainCategories": []
    },
    {
        "title": "Vô Thượng Sát Thần",
        "coverImage": "https://media.toidoc.vn/cover-truyen/10-vo-thuong-sat-than.png",
        "slug": "vo-thuong-sat-than",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 4.285714285714286,
        "totalView": 26409,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "https://media.toidoc.io/the-loai/tien-hiep.png",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4129,
                "metaDescription": "Danh sách truyện tiên hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện tiên hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện tiên hiệp, tiên hiệp, tiên hiệp hay, truyện tiên hiệp full hay, truyện tiên hiệp hay nhất, truyện tiên hiệp mới truyện tiên hiệp mới nhất, truyen tien hiep, truyện tiên hiệp audio, truyện tiên hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-tien-hiep/",
                "bgColor": "bg-tien-hiep",
                "orderCategory": 5,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "https://media.toidoc.io/the-loai/huyen-huyen.png",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 11396,
                "metaDescription": "Truyện huyền huyễn hay được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện huyền huyễn này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Huyền Huyễn, truyện huyền huyễn, truyện huyền huyễn hay, truyện huyền huyễn ngôn tình, truyện huyền huyễn cổ đại, truyện huyền huyễn full, list truyện huyền huyễn",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": "https://truyenfull.com/truyen-huyen-huyen/",
                "bgColor": "",
                "orderCategory": 12,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d03",
                "code": "di-gioi",
                "name": "Dị Giới",
                "image": "https://media.toidoc.io/the-loai/di-gioi.png",
                "slug": "/the-loai/di-gioi",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4756,
                "metaDescription": "Truyện dị giới full hay nhất có tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện dị giới này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Dị giới, truyện dị giới, truyen di gioi, truyện dị giới hay, truyện xuyên không dị giới, dị giới nữ cường, dị giới dược sư, dị giới sắc, dị giới full",
                "originUrl": "https://truyenfull.vn/the-loai/di-gioi/",
                "originUrlFullCom": "https://truyenfull.com/truyen-di-gioi/",
                "bgColor": "",
                "orderCategory": 18,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d07",
                "code": "xuyen-khong",
                "name": "Xuyên Không",
                "image": "https://media.toidoc.io/the-loai/xuyen-khong.png",
                "slug": "/the-loai/xuyen-khong",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 16656,
                "metaDescription": "Top các truyện xuyên không hấp dẫn cùng với bộ sưu tập của chúng tôi, bạn có thể xem ngay tại Toidoc. Sản phẩm được hỗ trợ trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện xuyên không, xuyên không, truyen xuyen khong, truyện xuyên không cổ đại, xuyên không quân sự, xuyên không y thuật, xuyên không hay nhất, truyện xuyên không nữ cường, xuyên không hay nhất mọi thời đại",
                "originUrl": "https://truyenfull.vn/the-loai/xuyen-khong/",
                "originUrlFullCom": "https://truyenfull.com/truyen-xuyen-khong/",
                "bgColor": "",
                "orderCategory": 15,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d09",
                "code": "trong-sinh",
                "name": "Trùng Sinh",
                "image": "https://media.toidoc.io/the-loai/trong-sinh.png",
                "slug": "/the-loai/trong-sinh",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 7130,
                "metaDescription": "Tuyển tập truyện Trùng Sinh (trùng sinh) hay mới nhất kể về sự hồi sinh của nhân vật chính vào một người khác có thể là xuyên không. Truyện được cập nhật nhanh tại Toidoc",
                "metaKeywords": "trọng sinh, trùng sinh, trong sinh, truyện trọng sinh, truyện trùng sinh, trọng sinh cổ đại, trọng sinh hay nhất, trọng sinh cổ đại hoàn, list truyện trọng sinh, trọng sinh hiện đại, truyện trọng sinh đam mỹ",
                "originUrl": "https://truyenfull.vn/the-loai/trong-sinh/",
                "originUrlFullCom": "https://truyenfull.com/truyen-trong-sinh/",
                "bgColor": "",
                "orderCategory": 14,
                "totalFollows": null,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "https://media.toidoc.io/the-loai/huyen-huyen.png",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 11396,
                "metaDescription": "Truyện huyền huyễn hay được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện huyền huyễn này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Huyền Huyễn, truyện huyền huyễn, truyện huyền huyễn hay, truyện huyền huyễn ngôn tình, truyện huyền huyễn cổ đại, truyện huyền huyễn full, list truyện huyền huyễn",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": "https://truyenfull.com/truyen-huyen-huyen/",
                "bgColor": "",
                "orderCategory": 12,
                "totalFollows": null,
                "type": null
            }
        ]
    },
    {
        "title": "Linh Vũ Thiên Hạ",
        "coverImage": "https://cdn.truyenfull.com/medias/covers/12/12429-linh-vu-thien-ha_cover_large.jpg",
        "slug": "linh-vu-thien-ha",
        "status": "ACTIVE",
        "thumbnail": "linh-vu-thien-ha-1711472319611.jpg",
        "rate": 4.0,
        "totalView": 32443,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 0,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d03",
                "code": "di-gioi",
                "name": "Dị Giới",
                "image": "",
                "slug": "/the-loai/di-gioi",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 0,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/di-gioi/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 0,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d07",
                "code": "xuyen-khong",
                "name": "Xuyên Không",
                "image": "",
                "slug": "/the-loai/xuyen-khong",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 0,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/xuyen-khong/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "https://media.toidoc.io/the-loai/tien-hiep.png",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4129,
                "metaDescription": "Danh sách truyện tiên hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện tiên hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện tiên hiệp, tiên hiệp, tiên hiệp hay, truyện tiên hiệp full hay, truyện tiên hiệp hay nhất, truyện tiên hiệp mới truyện tiên hiệp mới nhất, truyen tien hiep, truyện tiên hiệp audio, truyện tiên hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-tien-hiep/",
                "bgColor": "bg-tien-hiep",
                "orderCategory": 5,
                "totalFollows": 533,
                "type": null
            }
        ]
    },
    {
        "title": "Vô Tận Đan Điền",
        "coverImage": "https://cdn.truyenfull.com/medias/covers/1/1131-vo-tan-dan-dien_cover_large.jpg",
        "slug": "vo-tan-dan-dien",
        "status": "ACTIVE",
        "thumbnail": null,
        "rate": 4.6,
        "totalView": 2979,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 0,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d03",
                "code": "di-gioi",
                "name": "Dị Giới",
                "image": "",
                "slug": "/the-loai/di-gioi",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 0,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/di-gioi/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 0,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d09",
                "code": "trong-sinh",
                "name": "Trọng Sinh",
                "image": "",
                "slug": "/the-loai/trong-sinh",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 0,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/trong-sinh/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "https://media.toidoc.io/the-loai/tien-hiep.png",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 4129,
                "metaDescription": "Danh sách truyện tiên hiệp được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện tiên hiệp này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Truyện tiên hiệp, tiên hiệp, tiên hiệp hay, truyện tiên hiệp full hay, truyện tiên hiệp hay nhất, truyện tiên hiệp mới truyện tiên hiệp mới nhất, truyen tien hiep, truyện tiên hiệp audio, truyện tiên hiệp full hay nhất",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": "https://truyenfull.com/truyen-tien-hiep/",
                "bgColor": "bg-tien-hiep",
                "orderCategory": 5,
                "totalFollows": 533,
                "type": null
            }
        ]
    },
    {
        "title": "Thần Khống Thiên Hạ",
        "coverImage": "https://cdn.truyenfull.com/medias/covers/5/5256-than-khong-thien-ha_cover_large.jpg",
        "slug": "than-khong-thien-ha",
        "status": "ACTIVE",
        "thumbnail": "than-khong-thien-ha-1711472320330.jpg",
        "rate": 4.5,
        "totalView": 2870,
        "categories": [
            {
                "id": "63ba8d77cd9fcb5742949cfa",
                "code": "tien-hiep",
                "name": "Tiên Hiệp",
                "image": "",
                "slug": "/the-loai/tien-hiep",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 0,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/tien-hiep/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d03",
                "code": "di-gioi",
                "name": "Dị Giới",
                "image": "",
                "slug": "/the-loai/di-gioi",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 0,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/di-gioi/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            },
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 0,
                "metaDescription": "",
                "metaKeywords": "",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": null,
                "bgColor": "",
                "orderCategory": null,
                "totalFollows": null,
                "type": null
            }
        ],
        "mainCategories": [
            {
                "id": "63ba8d77cd9fcb5742949d02",
                "code": "huyen-huyen",
                "name": "Huyền Huyễn",
                "image": "https://media.toidoc.io/the-loai/huyen-huyen.png",
                "slug": "/the-loai/huyen-huyen",
                "shortDescription": "",
                "status": "ACTIVE",
                "totalStory": 11396,
                "metaDescription": "Truyện huyền huyễn hay được cập nhật liên tục tại Toidoc. Bạn có thể phân loại, sắp xếp, lọc các truyện huyền huyễn này trên nhiều thiết bị khác nhau.",
                "metaKeywords": "Huyền Huyễn, truyện huyền huyễn, truyện huyền huyễn hay, truyện huyền huyễn ngôn tình, truyện huyền huyễn cổ đại, truyện huyền huyễn full, list truyện huyền huyễn",
                "originUrl": "https://truyenfull.vn/the-loai/huyen-huyen/",
                "originUrlFullCom": "https://truyenfull.com/truyen-huyen-huyen/",
                "bgColor": "",
                "orderCategory": 12,
                "totalFollows": -2,
                "type": null
            }
        ]
    }
]

const formatNewStories = newStory.map((item) => ({
  ...item,
  categories: item.categories.map((category) => category.name)
}))

console.log("formatNewStories: ", formatNewStories)
  return (
    <div className="max-w-[1116px] md:grid-flow-col md:grid-cols-12 md:grid px-2 gap-x-4 space-y-4 sm:space-y-0">
      <div className="md:col-span-8 space-y-4">
        <NewStory data={formatNewStories} />
      </div>

      <div className="md:col-span-4 bg-[#F5F8FF] p-2 rounded-xl hidden md:block">
        <RatingList data={commentItem} />
      </div>
    </div>
  );
};

export default Section2;
